-- AlterTable
ALTER TABLE "Donation" ALTER COLUMN "Waehrung" DROP NOT NULL,
ALTER COLUMN "Buchungstext" DROP NOT NULL,
ALTER COLUMN "Verwendungszweck" DROP NOT NULL,
ALTER COLUMN "Kontonummer/IBAN" DROP NOT NULL,
ALTER COLUMN "BIC (SWIFT-Code)" DROP NOT NULL;
